### ISSUE TITLE
Feature: URL Context in note

### ISSUE THREAD

**Issue by javiavid** [lin-stephanie/obsidian-url-display#7]
### Goal or desired outcome

Show the URL in the note for more context

### Feature description

When you press ALT or CTRL on the note, the document is placed at the position of that URL.

**Comment by lin-stephanie** [comment]
maybe I got it, just click or other ways to navigate to the URL location in the note, right? If so, I already plan to work it out.

**Comment by lin-stephanie** [comment]
maybe I got it, just click or other ways to navigate to the URL location in the note, right? If so, I have planned to work it out.

**Comment by javiavid** [comment]
Thanks
